set tool "cdippy"
set exp_internal 1
set timeout 1.5

set testdata {
    {
        "A.1"
        {
            "NTH F ENGLAND"
            ""
            "NTH-PIC"
            ""
        } {
            "FAILS"
        }
    } {
        "A.2"
        {
            "LVP A ENGLAND"
            ""
            "LVP-IRI"
            ""
        } {
            "FAILS"
        }
    } {
        "A.3"
        {
            "KIE F GERMANY"
            ""
            "KIE-MUN"
            ""
        } {
            "FAILS"
        }
    } {
        "A.4"
        {
            "KIE F GERMANY"
            ""
            "KIE-KIE"
            ""
        } {
            "FAILS"
        }
    } {
        "A.5"
        {
            "NTH F ENGLAND"
            "YOR A ENGLAND"
            "LVP A ENGLAND"
            "LON F GERMANY"
            "WAL A GERMANY"
            ""
            "NTH C YOR-YOR"
            "YOR-YOR"
            "LVP S YOR-YOR"
            "LON-YOR"
            "WAL S LON-YOR"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "A.7"
        {
            "LON F ENGLAND"
            "NTH F ENGLAND"
            ""
            "LON-BEL"
            "NTH C LON-BEL"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "A.8"
        {
            "VEN A ITALY"
            "TYR A ITALY"
            "TRI F AUSTRIA"
            ""
            "VEN-TRI"
            "TYR S VEN-TRI"
            "TRI S TRI"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "A.9"
        {
            "ROM F ITALY"
            ""
            "ROM-VEN"
            ""
        } {
            "FAILS"
        }
    } {
        "A.10"
        {
            "VEN A AUSTRIA"
            "ROM F ITALY"
            "APU A ITALY"
            ""
            "ROM S APU-VEN"
            "APU-VEN"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "A.11"
        {
            "VIE A AUSTRIA"
            "VEN A ITALY"
            ""
            "VIE-TYR"
            "VEN-TYR"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "A.12"
        {
            "VIE A AUSTRIA"
            "MUN A GERMANY"
            "VEN A ITALY"
            ""
            "VIE-TYR"
            "MUN-TYR"
            "VEN-TYR"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
        }
    } {
        "B.1"
        {
            "POR F FRANCE"
            ""
            "POR-SPA"
            ""
        } {
            "FAILS"
        }
    } {
        "B.2"
        {
            "GAS F FRANCE"
            ""
            "GAS-SPA"
            ""
        } {
            "FAILS"
        }
    } {
        "B.3"
        {
            "GAS F FRANCE"
            ""
            "GAS-SPA(SC)"
            ""
        } {
            "FAILS"
        }
    } {
        "B.4"
        {
            "GAS F FRANCE"
            "MAR F FRANCE"
            "WES F ITALY"
            ""
            "GAS-SPA(NC)"
            "MAR S GAS-SPA"
            "WES-SPA(SC)"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "B.5"
        {
            "MAR F FRANCE"
            "SPA(NC) F FRANCE"
            "LYO F ITALY"
            ""
            "MAR-LYO"
            "SPA S MAR-LYO"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "B.6"
        {
            "IRI F ENGLAND"
            "NAO F ENGLAND"
            "SPA(NC) F FRANCE"
            "MAO F FRANCE"
            "LYO F ITALY"
            ""
            "IRI S NAO-MAO"
            "NAO-MAO"
            "SPA S MAO"
            "LYO-SPA(SC)"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    } {
        "B.11"
        {
            "SPA(NC) F FRANCE"
            ""
            "SPA-LYO"
            ""
        } {
            "FAILS"
        }
    } {
        "B.12"
        {
            "GAS A FRANCE"
            ""
            "GAS-SPA(NC)"
            ""
        } {
            "SUCCEEDS"
        }
    } {
        "B.13"
        {
            "BUL(NC) F TURKEY"
            "CON F TURKEY"
            ""
            "BUL-CON"
            "CON-BUL(SC)"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "C.1"
        {
            "ANK F TURKEY"
            "CON F TURKEY"
            "SMY A TURKEY"
            ""
            "ANK-CON"
            "CON-SMY"
            "SMY-ANK"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.2"
        {
            "ANK F TURKEY"
            "CON F TURKEY"
            "SMY A TURKEY"
            "BUL A TURKEY"
            ""
            "ANK-CON"
            "CON-SMY"
            "SMY-ANK"
            "BUL S ANK-CON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.3"
        {
            "ANK F TURKEY"
            "CON F TURKEY"
            "SMY A TURKEY"
            "BUL A TURKEY"
            ""
            "ANK-CON"
            "CON-SMY"
            "SMY-ANK"
            "BUL-CON"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
            "FAILS"
        }
    } {
        "C.4"
        {
            "TRI A AUSTRIA"
            "SER A AUSTRIA"
            "BUL A TURKEY"
            "AEG F TURKEY"
            "ION F TURKEY"
            "ADR F TURKEY"
            "NAP F ITALY"
            ""
            "TRI-SER"
            "SER-BUL"
            "BUL-TRI"
            "AEG C BUL-TRI"
            "ION C BUL-TRI"
            "ADR C BUL-TRI"
            "NAP-ION"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "C.5"
        {
            "TRI A AUSTRIA"
            "SER A AUSTRIA"
            "BUL A TURKEY"
            "AEG F TURKEY"
            "ION F TURKEY"
            "ADR F TURKEY"
            "NAP F ITALY"
            "TUN F ITALY"
            ""
            "TRI-SER"
            "SER-BUL"
            "BUL-TRI"
            "AEG C BUL-TRI"
            "ION C BUL-TRI"
            "ADR C BUL-TRI"
            "NAP-ION"
            "TUN S NAP-ION"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.6"
        {
            "NTH F ENGLAND"
            "LON A ENGLAND"
            "ENG F FRANCE"
            "BEL A FRANCE"
            ""
            "NTH C LON-BEL"
            "LON-BEL"
            "ENG C BEL-LON"
            "BEL-LON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.7"
        {
            "NTH F ENGLAND"
            "LON A ENGLAND"
            "ENG F FRANCE"
            "BEL A FRANCE"
            "BUR A FRANCE"
            ""
            "NTH C LON-BEL"
            "LON-BEL"
            "ENG C BEL-LON"
            "BEL-LON"
            "BUR-BEL"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    } {
        "D.1"
        {
            "ADR F AUSTRIA"
            "TRI A AUSTRIA"
            "VEN A ITALY"
            "TYR A ITALY"
            ""
            "ADR S TRI-VEN"
            "TRI-VEN"
            "TYR S VEN"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "D.2"
        {
            "ADR F AUSTRIA"
            "TRI A AUSTRIA"
            "VIE A AUSTRIA"
            "VEN A ITALY"
            "TYR A ITALY"
            ""
            "ADR S TRI-VEN"
            "TRI-VEN"
            "VIE-TYR"
            "TYR S VEN"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    } {
        "D.3"
        {
            "ADR F AUSTRIA"
            "TRI A AUSTRIA"
            "VEN A ITALY"
            "ION F ITALY"
            ""
            "ADR S TRI-VEN"
            "TRI-VEN"
            "ION-ADR"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
        }
    } {
        "D.4"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "BAL F RUSSIA"
            "PRU A RUSSIA"
            ""
            "BER S KIE"
            "KIE S BER"
            "BAL S PRU-BER"
            "PRU-BER"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.5"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "MUN A GERMANY"
            "BAL F RUSSIA"
            "PRU A RUSSIA"
            ""
            "BER S MUN-SIL"
            "KIE S BER"
            "MUN-SIL"
            "BAL S PRU-BER"
            "PRU-BER"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.6"
        {
            "BER A GERMANY"
            "BAL F GERMANY"
            "PRU F GERMANY"
            "LVN F RUSSIA"
            "BOT F RUSSIA"
            ""
            "BER-SWE"
            "BAL C BER-SWE"
            "PRU S BAL"
            "LVN-BAL"
            "BOT S LVN-BAL"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "D.7"
        {
            "BAL F GERMANY"
            "PRU F GERMANY"
            "LVN F RUSSIA"
            "BOT F RUSSIA"
            "FIN A RUSSIA"
            ""
            "BAL-SWE"
            "PRU S BAL-SWE"
            "LVN-BAL"
            "BOT S LVN-BAL"
            "FIN-SWE"
            ""
        } {
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.8"
        {
            "ION F AUSTRIA"
            "SER A AUSTRIA"
            "ALB A AUSTRIA"
            "GRE A TURKEY"
            "BUL A TURKEY"
            ""
            "SER S ALB-GRE"
            "ALB-GRE"
            "GRE-NAP"
            "BUL S GRE"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    } {
        "D.9"
        {
            "VEN A ITALY"
            "TYR A ITALY"
            "ALB A AUSTRIA"
            "TRI A AUSTRIA"
            ""
            "VEN-TRI"
            "TYR S VEN-TRI"
            "ALB S TRI-SER"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.10"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "MUN A GERMANY"
            ""
            "KIE-BER"
            "MUN S KIE-BER"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "D.11"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "MUN A GERMANY"
            "WAR A RUSSIA"
            ""
            "BER-PRU"
            "KIE-BER"
            "MUN S KIE-BER"
            "WAR-PRU"
            ""
        } {
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.12"
        {
            "TRI F AUSTRIA"
            "VIE A AUSTRIA"
            "VEN A ITALY"
            ""
            "VIE S VEN-TRI"
            "VEN-TRI"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.13"
        {
            "TRI F AUSTRIA"
            "VIE A AUSTRIA"
            "VEN A ITALY"
            "APU F ITALY"
            ""
            "TRI-ADR"
            "VIE S VEN-TRI"
            "VEN-TRI"
            "APU-ADR"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    } {
        "D.14"
        {
            "TRI F AUSTRIA"
            "VIE A AUSTRIA"
            "VEN A ITALY"
            "TYR A ITALY"
            "ADR F ITALY"
            ""
            "VIE S VEN-TRI"
            "VEN-TRI"
            "TYR S VEN-TRI"
            "ADR S VEN-TRI"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "D.15"
        {
            "CON F RUSSIA"
            "BLA F RUSSIA"
            "ANK F TURKEY"
            ""
            "CON S BLA-ANK"
            "BLA-ANK"
            "ANK-CON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.16"
        {
            "LON A ENGLAND"
            "NTH F ENGLAND"
            "ENG F FRANCE"
            "BEL A FRANCE"
            ""
            "NTH C BEL-LON"
            "ENG S BEL-LON"
            "BEL-LON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "D.17"
        {
            "CON F RUSSIA"
            "BLA F RUSSIA"
            "ANK F TURKEY"
            "SMY A TURKEY"
            "ARM A TURKEY"
            ""
            "CON S BLA-ANK"
            "BLA-ANK"
            "ANK-CON"
            "SMY S ANK-CON"
            "ARM-ANK"
            ""
        } {
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.18"
        {
            "CON F RUSSIA"
            "BLA F RUSSIA"
            "BUL A RUSSIA"
            "ANK F TURKEY"
            "SMY A TURKEY"
            "ARM A TURKEY"
            ""
            "CON S BLA-ANK"
            "BLA-ANK"
            "BUL S CON"
            "ANK-CON"
            "SMY S ANK-CON"
            "ARM-ANK"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.19"
        {
            "CON F RUSSIA"
            "BLA F RUSSIA"
            "SMY A RUSSIA"
            "ANK F TURKEY"
            ""
            "CON S BLA-ANK"
            "BLA-ANK"
            "SMY S ANK-CON"
            "ANK-CON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.20"
        {
            "LON F ENGLAND"
            "NTH F ENGLAND"
            "YOR A ENGLAND"
            "ENG F FRANCE"
            ""
            "LON S NTH-ENG"
            "NTH-ENG"
            "YOR-LON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.21"
        {
            "TRI F AUSTRIA"
            "VEN A ITALY"
            "TYR A ITALY"
            "MUN A GERMANY"
            "SIL A RUSSIA"
            "BER A RUSSIA"
            ""
            "VEN-TRI"
            "TYR S VEN-TRI"
            "MUN-TYR"
            "SIL-MUN"
            "BER S SIL-MUN"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "D.22"
        {
            "KIE F GERMANY"
            "BUR A GERMANY"
            "MUN A RUSSIA"
            "BER A RUSSIA"
            ""
            "KIE-MUN"
            "BUR S KIE-MUN"
            "MUN-KIE"
            "BER S MUN-KIE"
            ""
        } {
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "D.23"
        {
            "LYO F ITALY"
            "WES F ITALY"
            "SPA(NC) F FRANCE"
            "MAR F FRANCE"
            ""
            "LYO-SPA(SC)"
            "WES S LYO-SPA(SC)"
            "SPA-LYO"
            "MAR S SPA-LYO"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    } {
        "D.24"
        {
            "MAR A FRANCE"
            "SPA(SC) F FRANCE"
            "LYO F ITALY"
            "TYS F TURKEY"
            "WES F TURKEY"
            ""
            "MAR-LYO"
            "SPA S MAR-LYO"
            "TYS S WES-LYO"
            "WES-LYO"
            ""
        } {
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "D.25"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "BAL F RUSSIA"
            "PRU A RUSSIA"
            ""
            "BER S PRU"
            "KIE S BER"
            "BAL S PRU-BER"
            "PRU-BER"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.26"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "BAL F RUSSIA"
            "PRU A RUSSIA"
            ""
            "BER S PRU-SIL"
            "KIE S BER"
            "BAL S PRU-BER"
            "PRU-BER"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.27"
        {
            "SWE F ENGLAND"
            "DEN F ENGLAND"
            "BER A GERMANY"
            "BAL F RUSSIA"
            "PRU F RUSSIA"
            ""
            "SWE-BAL"
            "DEN S SWE-BAL"
            "BAL C BER-LVN"
            "PRU S BAL"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "D.28"
        {
            "BUD A AUSTRIA"
            "RUM F RUSSIA"
            "BLA F TURKEY"
            "BUL A TURKEY"
            ""
            "BUD S RUM"
            "RUM-HOL"
            "BLA-RUM"
            "BUL S BLA-RUM"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "D.29"
        {
            "BUD A AUSTRIA"
            "RUM F RUSSIA"
            "BLA F TURKEY"
            "BUL A TURKEY"
            ""
            "BUD S RUM"
            "RUM-BUL(SC)"
            "BLA-RUM"
            "BUL S BLA-RUM"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "D.30"
        {
            "AEG F ITALY"
            "CON F RUSSIA"
            "BLA F TURKEY"
            "BUL A TURKEY"
            ""
            "AEG S CON"
            "CON-BUL"
            "BLA-CON"
            "BUL S BLA-CON"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "D.31"
        {
            "RUM A AUSTRIA"
            "BLA F TURKEY"
            ""
            "RUM-ARM"
            "BLA S RUM-ARM"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "D.32"
        {
            "EDI F ENGLAND"
            "LVP A ENGLAND"
            "LON F FRANCE"
            "YOR A GERMANY"
            ""
            "EDI S LVP-YOR"
            "LVP-YOR"
            "LON S YOR"
            "YOR-HOL"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "D.33"
        {
            "SER A AUSTRIA"
            "VIE A AUSTRIA"
            "GAL A RUSSIA"
            "BUL A TURKEY"
            ""
            "SER-BUD"
            "VIE-BUD"
            "GAL S SER-BUD"
            "BUL-SER"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "D.34"
        {
            "BER A GERMANY"
            "SIL A GERMANY"
            "BAL F GERMANY"
            "PRU A ITALY"
            "WAR A RUSSIA"
            "LVN A RUSSIA"
            ""
            "BER-PRU"
            "SIL S BER-PRU"
            "BAL S BER-PRU"
            "PRU S LVN-PRU"
            "WAR S LVN-PRU"
            "LVN-PRU"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.1"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "SIL A GERMANY"
            "PRU A RUSSIA"
            ""
            "BER-PRU"
            "KIE-BER"
            "SIL S BER-PRU"
            "PRU-BER"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.2"
        {
            "BER A GERMANY"
            "KIE F GERMANY"
            "MUN A GERMANY"
            ""
            "BER-KIE"
            "KIE-BER"
            "MUN S BER-KIE"
            ""
        } {
            "FAILS"
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "E.3"
        {
            "BER A GERMANY"
            "MUN A GERMANY"
            "KIE F ENGLAND"
            ""
            "BER-KIE"
            "MUN S KIE-BER"
            "KIE-BER"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.4"
        {
            "HOL F GERMANY"
            "HEL F GERMANY"
            "SKA F GERMANY"
            "NTH F FRANCE"
            "BEL F FRANCE"
            "EDI F ENGLAND"
            "YOR F ENGLAND"
            "NWG F ENGLAND"
            "KIE A AUSTRIA"
            "RUH A AUSTRIA"
            ""
            "HOL-NTH"
            "HEL S HOL-NTH"
            "SKA S HOL-NTH"
            "NTH-HOL"
            "BEL S NTH-HOL"
            "EDI S NWG-NTH"
            "YOR S NWG-NTH"
            "NWG-NTH"
            "KIE S RUH-HOL"
            "RUH-HOL"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.5"
        {
            "HOL F GERMANY"
            "HEL F GERMANY"
            "SKA F GERMANY"
            "NTH F FRANCE"
            "BEL F FRANCE"
            "EDI F ENGLAND"
            "YOR F ENGLAND"
            "NWG F ENGLAND"
            "LON F ENGLAND"
            "KIE A AUSTRIA"
            "RUH A AUSTRIA"
            ""
            "HOL-NTH"
            "HEL S HOL-NTH"
            "SKA S HOL-NTH"
            "NTH-HOL"
            "BEL S NTH-HOL"
            "EDI S NWG-NTH"
            "YOR S NWG-NTH"
            "NWG-NTH"
            "LON S NWG-NTH"
            "KIE S RUH-HOL"
            "RUH-HOL"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.6"
        {
            "HOL F GERMANY"
            "HEL F GERMANY"
            "NTH F FRANCE"
            "BEL F FRANCE"
            "ENG F FRANCE"
            "KIE A AUSTRIA"
            "RUH A AUSTRIA"
            ""
            "HOL-NTH"
            "HEL S HOL-NTH"
            "NTH-HOL"
            "BEL S NTH-HOL"
            "ENG S HOL-NTH"
            "KIE S RUH-HOL"
            "RUH-HOL"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.7"
        {
            "NTH F ENGLAND"
            "YOR F ENGLAND"
            "HOL F GERMANY"
            "HEL F GERMANY"
            "SKA F RUSSIA"
            "NWY F RUSSIA"
            ""
            "YOR S NWY-NTH"
            "HOL S HEL-NTH"
            "HEL-NTH"
            "SKA S NWY-NTH"
            "NWY-NTH"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.8"
        {
            "NTH F ENGLAND"
            "YOR F ENGLAND"
            "HOL F GERMANY"
            "HEL F GERMANY"
            "SKA F RUSSIA"
            "NWY F RUSSIA"
            ""
            "NTH-NWY"
            "YOR S NWY-NTH"
            "HOL S HEL-NTH"
            "HEL-NTH"
            "SKA S NWY-NTH"
            "NWY-NTH"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.9"
        {
            "NTH F ENGLAND"
            "YOR F ENGLAND"
            "HOL F GERMANY"
            "HEL F GERMANY"
            "SKA F RUSSIA"
            "NWY F RUSSIA"
            ""
            "NTH-NWG"
            "YOR S NWY-NTH"
            "HOL S HEL-NTH"
            "HEL-NTH"
            "SKA S NWY-NTH"
            "NWY-NTH"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "E.10"
        {
            "NTH F ENGLAND"
            "YOR F ENGLAND"
            "HOL F GERMANY"
            "HEL F GERMANY"
            "DEN F GERMANY"
            "SKA F RUSSIA"
            "NWY F RUSSIA"
            ""
            "NTH-DEN"
            "YOR S NWY-NTH"
            "HOL S HEL-NTH"
            "HEL-NTH"
            "DEN-HEL"
            "SKA S NWY-NTH"
            "NWY-NTH"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "E.11"
        {
            "SPA A FRANCE"
            "MAO F FRANCE"
            "LYO F FRANCE"
            "MAR A GERMANY"
            "GAS A GERMANY"
            "POR F ITALY"
            "WES F ITALY"
            ""
            "SPA-POR"
            "MAO C SPA-POR"
            "LYO S POR-SPA"
            "MAR S GAS-SPA"
            "GAS-SPA"
            "POR-SPA(NC)"
            "WES S POR-SPA"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    }
}

global CDIPPY

foreach pattern $testdata {
    set name "DATC 6.[lindex $pattern 0]"
    set input [lindex $pattern 1]
    set output [lindex $pattern 2]

    eval "spawn $CDIPPY"

    foreach line $input {
        send "$line\n"
    }

    set failed 0

    foreach line $output {
        expect {
            -re "$line" { }
            default {
                fail $name
                set failed 1
                break
            }
        }
    }

    if {!$failed} {
        pass $name
    }
}
