set tool "cdippy"
set exp_internal 1
set timeout 1.5

set testdata {
    {
        "A.1"
        {
            "NTH F ENGLAND"
            ""
            "NTH-PIC"
            ""
        } {
            "FAILS"
        }
    } {
        "A.2"
        {
            "LVP A ENGLAND"
            ""
            "LVP-IRI"
            ""
        } {
            "FAILS"
        }
    } {
        "A.3"
        {
            "KIE F GERMANY"
            ""
            "KIE-MUN"
            ""
        } {
            "FAILS"
        }
    } {
        "A.4"
        {
            "KIE F GERMANY"
            ""
            "KIE-KIE"
            ""
        } {
            "FAILS"
        }
    } {
        "A.5"
        {
            "NTH F ENGLAND"
            "YOR A ENGLAND"
            "LVP A ENGLAND"
            "LON F GERMANY"
            "WAL A GERMANY"
            ""
            "NTH C YOR-YOR"
            "YOR-YOR"
            "LVP S YOR-YOR"
            "LON-YOR"
            "WAL S LON-YOR"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "A.7"
        {
            "LON F ENGLAND"
            "NTH F ENGLAND"
            ""
            "LON-BEL"
            "NTH C LON-BEL"
            ""
        } {
            "FAILS"
            "SUCCEEDS"
        }
    } {
        "A.8"
        {
            "VEN A ITALY"
            "TYR A ITALY"
            "TRI F AUSTRIA"
            ""
            "VEN-TRI"
            "TYR S VEN-TRI"
            "TRI S TRI"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "A.9"
        {
            "ROM F ITALY"
            ""
            "ROM-VEN"
            ""
        } {
            "FAILS"
        }
    } {
        "A.10"
        {
            "VEN A AUSTRIA"
            "ROM F ITALY"
            "APU A ITALY"
            ""
            "ROM S APU-VEN"
            "APU-VEN"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "A.11"
        {
            "VIE A AUSTRIA"
            "VEN A ITALY"
            ""
            "VIE-TYR"
            "VEN-TYR"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "A.12"
        {
            "VIE A AUSTRIA"
            "MUN A GERMANY"
            "VEN A ITALY"
            ""
            "VIE-TYR"
            "MUN-TYR"
            "VEN-TYR"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
        }
    } {
        "B.1"
        {
            "POR F FRANCE"
            ""
            "POR-SPA"
            ""
        } {
            "FAILS"
        }
    } {
        "B.2"
        {
            "GAS F FRANCE"
            ""
            "GAS-SPA"
            ""
        } {
            "FAILS"
        }
    } {
        "B.3"
        {
            "GAS F FRANCE"
            ""
            "GAS-SPA(SC)"
            ""
        } {
            "FAILS"
        }
    } {
        "B.4"
        {
            "GAS F FRANCE"
            "MAR F FRANCE"
            "WES F ITALY"
            ""
            "GAS-SPA(NC)"
            "MAR S GAS-SPA"
            "WES-SPA(SC)"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "B.5"
        {
            "MAR F FRANCE"
            "SPA(NC) F FRANCE"
            "LYO F ITALY"
            ""
            "MAR-LYO"
            "SPA S MAR-LYO"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "B.6"
        {
            "IRI F ENGLAND"
            "NAO F ENGLAND"
            "SPA(NC) F FRANCE"
            "MAO F FRANCE"
            "LYO F ITALY"
            ""
            "IRI S NAO-MAO"
            "NAO-MAO"
            "SPA S MAO"
            "LYO-SPA(SC)"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    } {
        "B.11"
        {
            "SPA(NC) F FRANCE"
            ""
            "SPA-LYO"
            ""
        } {
            "FAILS"
        }
    } {
        "B.12"
        {
            "GAS A FRANCE"
            ""
            "GAS-SPA(NC)"
            ""
        } {
            "SUCCEEDS"
        }
    } {
        "B.13"
        {
            "BUL(NC) F TURKEY"
            "CON F TURKEY"
            ""
            "BUL-CON"
            "CON-BUL(SC)"
            ""
        } {
            "FAILS"
            "FAILS"
        }
    } {
        "C.1"
        {
            "ANK F TURKEY"
            "CON F TURKEY"
            "SMY A TURKEY"
            ""
            "ANK-CON"
            "CON-SMY"
            "SMY-ANK"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.2"
        {
            "ANK F TURKEY"
            "CON F TURKEY"
            "SMY A TURKEY"
            "BUL A TURKEY"
            ""
            "ANK-CON"
            "CON-SMY"
            "SMY-ANK"
            "BUL S ANK-CON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.3"
        {
            "ANK F TURKEY"
            "CON F TURKEY"
            "SMY A TURKEY"
            "BUL A TURKEY"
            ""
            "ANK-CON"
            "CON-SMY"
            "SMY-ANK"
            "BUL-CON"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
            "FAILS"
        }
    } {
        "C.4"
        {
            "TRI A AUSTRIA"
            "SER A AUSTRIA"
            "BUL A TURKEY"
            "AEG F TURKEY"
            "ION F TURKEY"
            "ADR F TURKEY"
            "NAP F ITALY"
            ""
            "TRI-SER"
            "SER-BUL"
            "BUL-TRI"
            "AEG C BUL-TRI"
            "ION C BUL-TRI"
            "ADR C BUL-TRI"
            "NAP-ION"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "FAILS"
        }
    } {
        "C.5"
        {
            "TRI A AUSTRIA"
            "SER A AUSTRIA"
            "BUL A TURKEY"
            "AEG F TURKEY"
            "ION F TURKEY"
            "ADR F TURKEY"
            "NAP F ITALY"
            "TUN F ITALY"
            ""
            "TRI-SER"
            "SER-BUL"
            "BUL-TRI"
            "AEG C BUL-TRI"
            "ION C BUL-TRI"
            "ADR C BUL-TRI"
            "NAP-ION"
            "TUN S NAP-ION"
            ""
        } {
            "FAILS"
            "FAILS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.6"
        {
            "NTH F ENGLAND"
            "LON A ENGLAND"
            "ENG F FRANCE"
            "BEL A FRANCE"
            ""
            "NTH C LON-BEL"
            "LON-BEL"
            "ENG C BEL-LON"
            "BEL-LON"
            ""
        } {
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
            "SUCCEEDS"
        }
    } {
        "C.7"
        {
            "NTH F ENGLAND"
            "LON A ENGLAND"
            "ENG F FRANCE"
            "BEL A FRANCE"
            "BUR A FRANCE"
            ""
            "NTH C LON-BEL"
            "LON-BEL"
            "ENG C BEL-LON"
            "BEL-LON"
            "BUR-BEL"
            ""
        } {
            "SUCCEEDS"
            "FAILS"
            "SUCCEEDS"
            "FAILS"
            "FAILS"
        }
    }
}

global CDIPPY

foreach pattern $testdata {
    set name "DATC 6.[lindex $pattern 0]"
    set input [lindex $pattern 1]
    set output [lindex $pattern 2]

    eval "spawn $CDIPPY"

    foreach line $input {
        send "$line\n"
    }

    set failed 0

    foreach line $output {
        expect {
            -re "$line" { }
            default {
                fail $name
                set failed 1
                break
            }
        }
    }

    if {!$failed} {
        pass $name
    }
}
