/*
 *  cdippy: a classic Diplomacy adjudicator, in C
 *  Copyright (C) 2018 Simone Cimarelli a.k.a. AquilaIrreale
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#include <config.h>

#include <stdbool.h>

#include "map.h"

struct terr_info territories[TERR_N] = {
/* ADR */ {false, 0, 0, 0, {ALB, APU, ION, TRI, VEN}, 5,
                           {}, 0},
/* AEG */ {false, 0, 0, 0, {BUL, CON, EAS, GRE, ION, SMY}, 6,
                           {}, 0},
/* ALB */ {false, 0, 0, 0, {ADR, GRE, ION, TRI}, 4,
                           {GRE, SER, TRI}, 3},
/* ANK */ {false, 0, 0, 0, {ARM, BLA, CON}, 3,
                           {ARM, CON, SMY}, 3},
/* APU */ {false, 0, 0, 0, {ADR, ION, NAP, VEN}, 4,
                           {NAP, ROM, VEN}, 3},
/* ARM */ {false, 0, 0, 0, {ANK, BLA, SEV}, 3,
                           {ANK, SEV, SMY, SYR}, 4},
/* BAL */ {false, 0, 0, 0, {BER, BOT, DEN, KIE, LVN, PRU, SWE}, 7,
                           {}, 0},
/* BAR */ {false, 0, 0, 0, {NWG, NWY, STP}, 3,
                           {}, 0},
/* BEL */ {false, 0, 0, 0, {ENG, HOL, NTH, PIC}, 4,
                           {BUR, HOL, PIC, RUH}, 4},
/* BER */ {false, 0, 0, 0, {BAL, KIE, PRU}, 3,
                           {KIE, MUN, PRU, SIL}, 4},
/* BLA */ {false, 0, 0, 0, {ANK, ARM, BUL, CON, RUM, SEV}, 6,
                           {}, 0},
/* BOH */ {false, 0, 0, 0, {}, 0,
                           {GAL, MUN, SIL, TYR, VIE}, 5},
/* BOT */ {false, 0, 0, 0, {BAL, FIN, LVN, STP, SWE}, 5,
                           {}, 0},
/* BRE */ {false, 0, 0, 0, {ENG, GAS, MAO, PIC}, 4,
                           {GAS, PAR, PIC}, 3},
/* BUD */ {false, 0, 0, 0, {}, 0,
                           {GAL, RUM, SER, TRI, VIE}, 5},
/* BUL */ {false, 0, 0, 0, {AEG, BLA, CON, GRE, RUM}, 5,
                           {CON, GRE, RUM, SER}, 4},
/* BUR */ {false, 0, 0, 0, {}, 0,
                           {BEL, GAS, MAR, MUN, PAR, PIC, RUH}, 7},
/* CLY */ {false, 0, 0, 0, {EDI, LVP, NAO, NWG}, 4,
                           {EDI, LVP}, 2},
/* CON */ {false, 0, 0, 0, {AEG, ANK, BLA, BUL, SMY}, 5,
                           {ANK, BUL, SMY}, 3},
/* DEN */ {false, 0, 0, 0, {BAL, HEL, KIE, NTH, SKA, SWE}, 6,
                           {KIE, SWE}, 2},
/* EAS */ {false, 0, 0, 0, {AEG, ION, SMY, SYR}, 4,
                           {}, 0},
/* EDI */ {false, 0, 0, 0, {CLY, NTH, NWG, YOR}, 4,
                           {CLY, LVP, YOR}, 3},
/* ENG */ {false, 0, 0, 0, {BEL, BRE, IRI, LON, MAO, NTH, PIC, WAL}, 8,
                           {}, 0},
/* FIN */ {false, 0, 0, 0, {BOT, STP, SWE}, 3,
                           {NWY, STP, SWE}, 3},
/* GAL */ {false, 0, 0, 0, {}, 0,
                           {BOH, BUD, RUM, SIL, UKR, VIE, WAR}, 7},
/* GAS */ {false, 0, 0, 0, {BRE, MAO, SPA}, 3,
                           {BRE, BUR, MAR, PAR, SPA}, 5},
/* GRE */ {false, 0, 0, 0, {AEG, ALB, BUL, ION}, 4,
                           {ALB, BUL, SER}, 3},
/* HEL */ {false, 0, 0, 0, {DEN, HOL, KIE, NTH}, 4,
                           {}, 0},
/* HOL */ {false, 0, 0, 0, {BEL, HEL, KIE, NTH}, 4,
                           {BEL, KIE, RUH}, 3},
/* ION */ {false, 0, 0, 0, {ADR, AEG, ALB, APU, EAS, GRE, NAP, TUN, TYS}, 9,
                           {}, 0},
/* IRI */ {false, 0, 0, 0, {ENG, LVP, MAO, NAO, WAL}, 5,
                           {}, 0},
/* KIE */ {false, 0, 0, 0, {BAL, BER, DEN, HEL, HOL}, 5,
                           {BER, DEN, HOL, MUN, RUH}, 5},
/* LON */ {false, 0, 0, 0, {ENG, NTH, WAL, YOR}, 4,
                           {WAL, YOR}, 2},
/* LVN */ {false, 0, 0, 0, {BAL, BOT, PRU, STP}, 4,
                           {MOS, PRU, STP, WAR}, 4},
/* LVP */ {false, 0, 0, 0, {CLY, IRI, NAO, WAL}, 4,
                           {CLY, EDI, WAL, YOR}, 4},
/* LYO */ {false, 0, 0, 0, {MAR, PIE, SPA, TUS, TYS, WES}, 6,
                           {}, 0},
/* MAO */ {false, 0, 0, 0, {BRE, ENG, GAS, IRI, NAF, NAO, POR, SPA, WES}, 9,
                           {}, 0},
/* MAR */ {false, 0, 0, 0, {LYO, PIE, SPA}, 3,
                           {BUR, GAS, PIE, SPA}, 4},
/* MOS */ {false, 0, 0, 0, {}, 0,
                           {LVN, SEV, STP, UKR, WAR}, 5},
/* MUN */ {false, 0, 0, 0, {}, 0,
                           {BER, BOH, BUR, KIE, RUH, SIL, TYR}, 7},
/* NAF */ {false, 0, 0, 0, {MAO, TUN, WES}, 3,
                           {TUN}, 1},
/* NAO */ {false, 0, 0, 0, {CLY, IRI, LVP, MAO, NWG}, 5,
                           {}, 0},
/* NAP */ {false, 0, 0, 0, {APU, ION, ROM, TYS}, 4,
                           {APU, ROM}, 2},
/* NTH */ {false, 0, 0, 0, {BEL, DEN, EDI, ENG, HEL, HOL, LON, NWG, NWY, SKA, YOR}, 11,
                           {}, 0},
/* NWG */ {false, 0, 0, 0, {BAR, CLY, EDI, NAO, NTH, NWY}, 6,
                           {}, 0},
/* NWY */ {false, 0, 0, 0, {BAR, NTH, NWG, SKA, STP, SWE}, 6,
                           {FIN, STP, SWE}, 3},
/* PAR */ {false, 0, 0, 0, {}, 0,
                           {BRE, BUR, GAS, PIC}, 4},
/* PIC */ {false, 0, 0, 0, {BEL, BRE, ENG}, 3,
                           {BEL, BRE, BUR, PAR}, 4},
/* PIE */ {false, 0, 0, 0, {LYO, MAR, TUS}, 3,
                           {MAR, TUS, TYR, VEN}, 4},
/* POR */ {false, 0, 0, 0, {MAO, SPA}, 2,
                           {SPA}, 1},
/* PRU */ {false, 0, 0, 0, {BAL, BER, LVN}, 3,
                           {BER, LVN, SIL, WAR}, 4},
/* ROM */ {false, 0, 0, 0, {NAP, TUS, TYS}, 3,
                           {APU, NAP, TUS, VEN}, 4},
/* RUH */ {false, 0, 0, 0, {}, 0,
                           {BEL, BUR, HOL, KIE, MUN}, 5},
/* RUM */ {false, 0, 0, 0, {BLA, BUL, SEV}, 3,
                           {BUD, BUL, GAL, SER, SEV, UKR}, 6},
/* SER */ {false, 0, 0, 0, {}, 0,
                           {ALB, BUD, BUL, GRE, RUM, TRI}, 6},
/* SEV */ {false, 0, 0, 0, {ARM, BLA, RUM}, 3,
                           {ARM, MOS, RUM, UKR}, 4},
/* SIL */ {false, 0, 0, 0, {}, 0,
                           {BER, BOH, GAL, MUN, PRU, WAR}, 6},
/* SKA */ {false, 0, 0, 0, {DEN, NTH, NWY, SWE}, 4,
                           {}, 0},
/* SMY */ {false, 0, 0, 0, {AEG, CON, EAS, SYR}, 4,
                           {ANK, ARM, CON, SYR}, 4},
/* SPA */ {false, 0, 0, 0, {GAS, LYO, MAO, MAR, POR, WES}, 6,
                           {GAS, MAR, POR}, 3},
/* STP */ {false, 0, 0, 0, {BAR, BOT, FIN, LVN, NWY}, 5,
                           {FIN, LVN, MOS, NWY}, 4},
/* SWE */ {false, 0, 0, 0, {BAL, BOT, DEN, FIN, NWY, SKA}, 6,
                           {DEN, FIN, NWY}, 3},
/* SYR */ {false, 0, 0, 0, {EAS, SMY}, 2,
                           {ARM, SMY}, 2},
/* TRI */ {false, 0, 0, 0, {ADR, ALB, VEN}, 3,
                           {ALB, BUD, SER, TYR, VEN, VIE}, 6},
/* TUN */ {false, 0, 0, 0, {ION, NAF, TYS, WES}, 4,
                           {NAF}, 1},
/* TUS */ {false, 0, 0, 0, {LYO, PIE, ROM, TYS}, 4,
                           {PIE, ROM, VEN}, 3},
/* TYR */ {false, 0, 0, 0, {}, 0,
                           {BOH, MUN, PIE, TRI, VEN, VIE}, 6},
/* TYS */ {false, 0, 0, 0, {ION, LYO, NAP, ROM, TUN, TUS, WES}, 7,
                           {}, 0},
/* UKR */ {false, 0, 0, 0, {}, 0,
                           {GAL, MOS, RUM, SEV, WAR}, 5},
/* VEN */ {false, 0, 0, 0, {ADR, APU, TRI}, 3,
                           {APU, PIE, ROM, TRI, TUS, TYR}, 6},
/* VIE */ {false, 0, 0, 0, {}, 0,
                           {BOH, BUD, GAL, TRI, TYR}, 5},
/* WAL */ {false, 0, 0, 0, {ENG, IRI, LON, LVP}, 4,
                           {LON, LVP, YOR}, 3},
/* WAR */ {false, 0, 0, 0, {}, 0,
                           {GAL, LVN, MOS, PRU, SIL, UKR}, 6},
/* WES */ {false, 0, 0, 0, {LYO, MAO, NAF, SPA, TUN, TYS}, 6,
                           {}, 0},
/* YOR */ {false, 0, 0, 0, {EDI, LON, NTH}, 3,
                           {EDI, LON, LVP, WAL}, 4}
};
